### ISSUE TITLE
question about building FastClick

### ISSUE THREAD

**Issue by rexlily** [cheetahlb/cheetah-fastclick#1]
Hello：
I followed your installation steps, after ‘Export RTE_SDK  and RTE_TARGET’, and type ’./configure’
```
Configuration Summary:
    C     Compiler:              gcc
    C++   Compiler:              g++

          Batching:              yes
              Flow:              no

    DPDK   support:              no
    Netmap support:              no
    PCAP   support:              yes

    RE2    support:              no
    HTTPD  support:              no
    JSON   support:              no
```
if I input ‘./configure --enable-dpdk --enable-multithread --disable-linuxmodule --enable-intel-cpu --enable-user-multithread --verbose --enable-select=poll CFLAGS="-O3" CXXFLAGS="-std=c++11 -O3" --disable-dynamic-linking --enable-poll --enable-bound-port-transfer --enable-local --enble-flow --enable-cheetah --disable-task-stats --enable-cpu-load’
```
configure: error: unrecognized option: `--enble-flow'
Try `./configure --help' for more information
```
if I input ‘./configure --enable-dpdk --enable-multithread '
```
Cannot find $RTE_SDK_BIN/include/rte_eal.h for DPDK.
Define $RTE_SDK and $RTE_TARGET as per DPDK documentation,
or install DPDK using meson, or he system package manager.
```

I don't know which part went wrong. The dpdk mentioned in the previous step is already installed and ready to use.
Thank you.

**Comment by tbarbette** [comment]
Hi !  There is a mispell in --enable-flow. But that is not what is preventing the compilation.

Which DPDK version are you using ?  ls  $RTE_SDK/$RTE_TARGET works ?

**Comment by rexlily** [comment]
DPDK version is 19.11.
I enter the export command to check and it shows
```
declare -x RTE_SDK="/home/lily/dpdk-19.11"
declare -x RTE_TARGET="x86_64-native-linuxapp-gcc"
```

**Comment by tbarbette** [comment]
Can you give me the config.log then ?

**Comment by rexlily** [comment]
[link](https://github.com/rexlily/LB-learning/blob/master/config.log) is here.
It seems that I am missing some header files.
The error seems to be related to the following.
```
 #include <ac_nonexistent.h>
 #include <machine/endian.h>
 #include <sys/event.h>
 #include <net/if_dl.h>
 #include <net/if_tap.h>
 #include <net/if_tun.h>
 #include <net/if_types.h>
 #include <net/bpf.h>
 #include <mbgdevio.h>
 #include <microhttpd.h>
 #include <re2/re2.h>
 #include <hs/hs.h>

conftest.cpp: In function 'int main()':
conftest.cpp:52:10: error: 'align_val_t' is not a member of 'std'
     std::align_val_t al{64};
          ^~~~~~~~~~~
conftest.cpp:52:10: note: suggested alternative: 'alignment_of'
     std::align_val_t al{64};
          ^~~~~~~~~~~
          alignment_of
conftest.cpp:53:31: error: 'al' was not declared in this scope
     void* a = operator new(sz,al);
                               ^~
conftest.cpp:53:31: note: suggested alternative: 'a'
     void* a = operator new(sz,al);
                               ^~
```

**Comment by tbarbette** [comment]
No that is a test. The problem is later, DPDK cannot be found. What does "ls  $RTE_SDK/$RTE_TARGET" gives ? You installed DPDK with make or meson ?  Through the dpdk setup menu ?

**Comment by rexlily** [comment]
I thought that the dpdk was installed by following the steps of  [Qucik Start](http://core.dpdk.org/doc/quick-start/), because the test programs and examples can be run.  Later, I installed it through the dpdk setup menu, then configured again and found it can support dpdk. 
This is a new [log file](https://github.com/rexlily/LB-learning/blob/master/config.log).
So the next step is `make` to build FastClick. I will learn how to use it. 
Thank you.

**Comment by tbarbette** [comment]
Normally quick start should be enough... I'll verify on my end. Thanks for the debugging !

**Comment by tbarbette** [comment]
Ok actually the new quick start use slightly different method (build in DPDK /build). I'll make fastclick compatible with that one and merge in. Thanks!

**Comment by tbarbette** [comment]
It's actually a DPDK bug... External apps cannot build if you follow the tutorial steps... I'll change the tutorial.
